#!/usr/bin/env bash
# this script extracts the following information from an apache log file:
# 1) IP address, 2) HTTP status code
awk '{print $1 " " $9}' apache-access.log | sort | uniq --count | sort --reverse --general-numeric-sort
