#!/usr/bin/env bash
# this script prints 12 hours of clock time
hour="0"
while [ $hour -le 12 ]; do
	echo -n "Hour: "
	echo $hour
	min="1"
	while [ $min -lt 60 ]; do
		echo $min
		min=$((min+1));
	done
	hour=$((hour+1));
done
